version: '3.8'
services:
  node1:
    build:
      context: ./node1
    ports:
      - "5001:5000"

  node2:
    build:
      context: ./node2
    ports:
      - "5002:5000"

  node3:
    build:
      context: ./node3
    ports:
      - "5003:5000"

  central_node:
    build:
      context: ./central_node
    ports:
      - "5000:5000"
    depends_on:
      - node1
      - node2
      - node3
